# "Project2-3"
> "ML을 이용한 대출 채무이행 판별"

- toc:true
- branch: master
- badges: true
- comments: true
- author: channee
- categories: [jupyter, ML, MachineLearning]

##### pandas groupby 단일 aggregation 함수 사용
* groupby SK_ID_CURR
* SK_ID_CURR별 건수, AMT_CREDIT에 대한 평균, 최대 값

In [ ]:
prev.groupby('SK_ID_CURR')

In [ ]:
# DataFrameGroupby 생성. 
prev_group= prev.groupby('SK_ID_CURR')

# DataFrameGroupby 객체에 aggregation함수 수행 결과를 저장한 DataFrame 생성 및 aggregation값 저장. 
prev_agg = pd.DataFrame()
prev_agg['CNT'] = prev_group['SK_ID_CURR'].count()
prev_agg['AVG_CREDIT'] = prev_group['AMT_CREDIT'].mean()
prev_agg['MAX_CREDIT'] = prev_group['AMT_CREDIT'].max()

# groupby 컬럼값이 DataFrame의 Index가 됨. 컬럼으로 변환하려면 reset_index()로 변환 필요. 
prev_agg.head(10)

            CNT     AVG_CREDIT  MAX_CREDIT
SK_ID_CURR
100001        1   23787.000000     23787.0
100002        1  179055.000000    179055.0
100003        3  484191.000000   1035882.0
100004        1   20106.000000     20106.0
100005        2   20076.750000     40153.5
100006        9  291695.500000    906615.0
100007        6  166638.750000    284400.0
100008        5  162767.700000    501975.0
100009        7   70137.642857     98239.5
100010        1  260811.000000    260811.0

##### groupby agg()함수를 이용하여 여러개의 aggregation 함수 적용

In [ ]:
prev_group = prev.groupby('SK_ID_CURR')

# DataFrameGroupby의 agg() 함수를 이용하여 여러개의 aggregation 함수 적용
prev_agg1 = prev_group['AMT_CREDIT'].agg(['mean', 'max', 'sum'])
prev_agg2 = prev_group['AMT_ANNUITY'].agg(['mean', 'max', 'sum'])
# merge를 이용하여 두개의 DataFrame 결합. 
prev_agg = prev_agg1.merge(prev_agg2, on='SK_ID_CURR', how='inner')
prev_agg.head(10)

,mean_x,max_x,sum_x,mean_y,max_y,sum_y
SK_ID_CURR,,,,,,
100001,23787.000000,23787.0,23787.0,3951.000000,3951.000,3951.000
100002,179055.000000,179055.0,179055.0,9251.775000,9251.775,9251.775
100003,484191.000000,1035882.0,1452573.0,56553.990000,98356.995,169661.970
100004,20106.000000,20106.0,20106.0,5357.250000,5357.250,5357.250
100005,20076.750000,40153.5,40153.5,4813.200000,4813.200,4813.200
100006,291695.500000,906615.0,2625259.5,23651.175000,39954.510,141907.050
100007,166638.750000,284400.0,999832.5,12278.805000,22678.785,73672.830
100008,162767.700000,501975.0,813838.5,15839.696250,25309.575,63358.785
100009,70137.642857,98239.5,490963.5,10051.412143,17341.605,70359.885
100010,260811.000000,260811.0,260811.0,27463.410000,27463.410,27463.410

##### agg()에 dictionary를 이용하여 groupby 적용

In [ ]:
agg_dict = {
    'SK_ID_CURR':['count'],
    'AMT_CREDIT':['mean', 'max', 'sum'],
    'AMT_ANNUITY':['mean', 'max', 'sum'], 
    'AMT_APPLICATION':['mean', 'max', 'sum'],
    'AMT_DOWN_PAYMENT':['mean', 'max', 'sum'],
    'AMT_GOODS_PRICE':['mean', 'max', 'sum']
}

prev_group = prev.groupby('SK_ID_CURR')
prev_amt_agg = prev_group.agg(agg_dict)
prev_amt_agg.head()

           SK_ID_CURR AMT_CREDIT                       AMT_ANNUITY             \
                count       mean        max        sum        mean        max
SK_ID_CURR
100001              1   23787.00    23787.0    23787.0    3951.000   3951.000
100002              1  179055.00   179055.0   179055.0    9251.775   9251.775
100003              3  484191.00  1035882.0  1452573.0   56553.990  98356.995
100004              1   20106.00    20106.0    20106.0    5357.250   5357.250
100005              2   20076.75    40153.5    40153.5    4813.200   4813.200

                       AMT_APPLICATION                      AMT_DOWN_PAYMENT  \
                   sum            mean       max        sum             mean
SK_ID_CURR
100001        3951.000        24835.50   24835.5    24835.5           2520.0
100002        9251.775       179055.00  179055.0   179055.0              0.0
100003      169661.970       435436.50  900000.0  1306309.5           3442.5
100004        5357.250        24282.00   24282.0    24282.0           4860.0
100005        4813.200        22308.75   44617.5    44617.5           4464.0

                           AMT_GOODS_PRICE
               max     sum            mean       max        sum
SK_ID_CURR
100001      2520.0  2520.0         24835.5   24835.5    24835.5
100002         0.0     0.0        179055.0  179055.0   179055.0
100003      6885.0  6885.0        435436.5  900000.0  1306309.5
100004      4860.0  4860.0         24282.0   24282.0    24282.0
100005      4464.0  4464.0         44617.5   44617.5    44617.5

##### grouby agg 로 만들어진  Multi index 컬럼 변경. 
* MultiIndex로 되어 있는 컬럼명 확인
* MultiIndex 컬럼명을 _로 연결하여 컬럼명 변경.

In [ ]:
prev_amt_agg.columns

MultiIndex([(      'SK_ID_CURR', 'count'),
            (      'AMT_CREDIT',  'mean'),
            (      'AMT_CREDIT',   'max'),
            (      'AMT_CREDIT',   'sum'),
            (     'AMT_ANNUITY',  'mean'),
            (     'AMT_ANNUITY',   'max'),
            (     'AMT_ANNUITY',   'sum'),
            ( 'AMT_APPLICATION',  'mean'),
            ( 'AMT_APPLICATION',   'max'),
            ( 'AMT_APPLICATION',   'sum'),
            ('AMT_DOWN_PAYMENT',  'mean'),
            ('AMT_DOWN_PAYMENT',   'max'),
            ('AMT_DOWN_PAYMENT',   'sum'),
            ( 'AMT_GOODS_PRICE',  'mean'),
            ( 'AMT_GOODS_PRICE',   'max'),
            ( 'AMT_GOODS_PRICE',   'sum')],
           )

In [ ]:
# multi index 컬럼을 '_'로 연결하여 컬럼명 변경
prev_amt_agg.columns = ["PREV_"+"_".join(x).upper() for x in prev_amt_agg.columns.ravel()]

In [ ]:
prev_amt_agg.head()

,PREV_SK_ID_CURR_COUNT,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_SUM,PREV_AMT_ANNUITY_MEAN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_SUM,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_SUM,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MAX,PREV_AMT_DOWN_PAYMENT_SUM,PREV_AMT_GOODS_PRICE_MEAN,PREV_AMT_GOODS_PRICE_MAX,PREV_AMT_GOODS_PRICE_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,
100001,1,23787.00,23787.0,23787.0,3951.000,3951.000,3951.000,24835.50,24835.5,24835.5,2520.0,2520.0,2520.0,24835.5,24835.5,24835.5
100002,1,179055.00,179055.0,179055.0,9251.775,9251.775,9251.775,179055.00,179055.0,179055.0,0.0,0.0,0.0,179055.0,179055.0,179055.0
100003,3,484191.00,1035882.0,1452573.0,56553.990,98356.995,169661.970,435436.50,900000.0,1306309.5,3442.5,6885.0,6885.0,435436.5,900000.0,1306309.5
100004,1,20106.00,20106.0,20106.0,5357.250,5357.250,5357.250,24282.00,24282.0,24282.0,4860.0,4860.0,4860.0,24282.0,24282.0,24282.0
100005,2,20076.75,40153.5,40153.5,4813.200,4813.200,4813.200,22308.75,44617.5,44617.5,4464.0,4464.0,4464.0,44617.5,44617.5,44617.5

##### prev 피처 가공. 대출 신청액 대비 다른 금액 차이 및 비율 생성.

In [ ]:
# 대출 신청 금액과 실제 대출액/대출 상품금액 차이 및 비율
prev['PREV_CREDIT_DIFF'] = prev['AMT_APPLICATION'] - prev['AMT_CREDIT']
prev['PREV_GOODS_DIFF'] = prev['AMT_APPLICATION'] - prev['AMT_GOODS_PRICE']
prev['PREV_CREDIT_APPL_RATIO'] = prev['AMT_CREDIT']/prev['AMT_APPLICATION']
prev['PREV_ANNUITY_APPL_RATIO'] = prev['AMT_ANNUITY']/prev['AMT_APPLICATION']
prev['PREV_GOODS_APPL_RATIO'] = prev['AMT_GOODS_PRICE']/prev['AMT_APPLICATION']

##### DAYS_XXX 피처의 365243 을 NULL로 변환하고, 첫번째 만기일과 마지막 만기일까지의 기간 가공

In [ ]:
prev['DAYS_FIRST_DRAWING'].replace(365243, np.nan, inplace= True)
prev['DAYS_FIRST_DUE'].replace(365243, np.nan, inplace= True)
prev['DAYS_LAST_DUE_1ST_VERSION'].replace(365243, np.nan, inplace= True)
prev['DAYS_LAST_DUE'].replace(365243, np.nan, inplace= True)
prev['DAYS_TERMINATION'].replace(365243, np.nan, inplace= True)
# 첫번째 만기일과 마지막 만기일까지의 기간
prev['PREV_DAYS_LAST_DUE_DIFF'] = prev['DAYS_LAST_DUE_1ST_VERSION'] - prev['DAYS_LAST_DUE']

##### 기존 이자율 관련 컬럼이 null이 많아서 새롭게 간단한 이자율을 대출 금액과 대출 금액 납부 횟수를 기반으로 계산

In [ ]:
# 매월 납부 금액과 납부 횟수 곱해서 전체 납부 금액 구함. 
all_pay = prev['AMT_ANNUITY'] * prev['CNT_PAYMENT']
# 전체 납부 금액 대비 AMT_CREDIT 비율을 구하고 여기에 다시 납부횟수로 나누어서 이자율 계산. 
prev['PREV_INTERESTS_RATE'] = (all_pay/prev['AMT_CREDIT'] - 1)/prev['CNT_PAYMENT']

In [ ]:
prev.iloc[:, -7:].head(10)

,PREV_CREDIT_DIFF,PREV_GOODS_DIFF,PREV_CREDIT_APPL_RATIO,PREV_ANNUITY_APPL_RATIO,PREV_GOODS_APPL_RATIO,PREV_DAYS_LAST_DUE_DIFF,PREV_INTERESTS_RATE
0,0.0,0.0,1.000000,0.100929,1.0,342.0,0.017596
1,-72171.0,0.0,1.118800,0.041463,1.0,NaN,0.009282
2,-23944.5,0.0,1.212840,0.133873,1.0,NaN,0.027047
3,-20790.0,0.0,1.046200,0.104536,1.0,30.0,0.016587
4,-66555.0,0.0,1.197200,0.094591,1.0,NaN,0.037343
5,-25573.5,0.0,1.081186,0.075251,1.0,0.0,0.014044
6,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8,0.0,NaN,NaN,NaN,NaN,NaN,NaN
9,0.0,NaN,NaN,NaN,NaN,NaN,NaN

##### 기존 대출 금액, 대출 상태 관련 피처들과 이들을 가공하여 만들어진 새로운 컬럼들로 aggregation 수행.

In [ ]:
# 새롭게 생성된 대출 신청액 대비 다른 금액 차이 및 비율로 aggregation 수행. 
agg_dict = {
     # 기존 컬럼. 
    'SK_ID_CURR':['count'],
    'AMT_CREDIT':['mean', 'max', 'sum'],
    'AMT_ANNUITY':['mean', 'max', 'sum'], 
    'AMT_APPLICATION':['mean', 'max', 'sum'],
    'AMT_DOWN_PAYMENT':['mean', 'max', 'sum'],
    'AMT_GOODS_PRICE':['mean', 'max', 'sum'],
    'RATE_DOWN_PAYMENT': ['min', 'max', 'mean'],
    'DAYS_DECISION': ['min', 'max', 'mean'],
    'CNT_PAYMENT': ['mean', 'sum'],
    # 가공 컬럼
    'PREV_CREDIT_DIFF':['mean', 'max', 'sum'], 
    'PREV_CREDIT_APPL_RATIO':['mean', 'max'],
    'PREV_GOODS_DIFF':['mean', 'max', 'sum'],
    'PREV_GOODS_APPL_RATIO':['mean', 'max'],
    'PREV_DAYS_LAST_DUE_DIFF':['mean', 'max', 'sum'],
    'PREV_INTERESTS_RATE':['mean', 'max']
}

prev_group = prev.groupby('SK_ID_CURR')
prev_amt_agg = prev_group.agg(agg_dict)

# multi index 컬럼을 '_'로 연결하여 컬럼명 변경
prev_amt_agg.columns = ["PREV_"+ "_".join(x).upper() for x in prev_amt_agg.columns.ravel()]

In [ ]:
prev_amt_agg.head()

,PREV_SK_ID_CURR_COUNT,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_SUM,PREV_AMT_ANNUITY_MEAN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_SUM,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_SUM,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MAX,PREV_AMT_DOWN_PAYMENT_SUM,PREV_AMT_GOODS_PRICE_MEAN,PREV_AMT_GOODS_PRICE_MAX,PREV_AMT_GOODS_PRICE_SUM,PREV_RATE_DOWN_PAYMENT_MIN,PREV_RATE_DOWN_PAYMENT_MAX,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_DAYS_DECISION_MIN,PREV_DAYS_DECISION_MAX,PREV_DAYS_DECISION_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_CNT_PAYMENT_SUM,PREV_PREV_CREDIT_DIFF_MEAN,PREV_PREV_CREDIT_DIFF_MAX,PREV_PREV_CREDIT_DIFF_SUM,PREV_PREV_CREDIT_APPL_RATIO_MEAN,PREV_PREV_CREDIT_APPL_RATIO_MAX,PREV_PREV_GOODS_DIFF_MEAN,PREV_PREV_GOODS_DIFF_MAX,PREV_PREV_GOODS_DIFF_SUM,PREV_PREV_GOODS_APPL_RATIO_MEAN,PREV_PREV_GOODS_APPL_RATIO_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_MEAN,PREV_PREV_DAYS_LAST_DUE_DIFF_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_SUM,PREV_PREV_INTERESTS_RATE_MEAN,PREV_PREV_INTERESTS_RATE_MAX
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,1,23787.00,23787.0,23787.0,3951.000,3951.000,3951.000,24835.50,24835.5,24835.5,2520.0,2520.0,2520.0,24835.5,24835.5,24835.5,0.104326,0.104326,0.104326,-1740,-1740,-1740.0,8.0,8.0,1048.5,1048.5,1048.5,0.957782,0.957782,0.0,0.0,0.0,1.0,1.0,120.0,120.0,120.0,0.041099,0.041099
100002,1,179055.00,179055.0,179055.0,9251.775,9251.775,9251.775,179055.00,179055.0,179055.0,0.0,0.0,0.0,179055.0,179055.0,179055.0,0.000000,0.000000,0.000000,-606,-606,-606.0,24.0,24.0,0.0,0.0,0.0,1.000000,1.000000,0.0,0.0,0.0,1.0,1.0,150.0,150.0,150.0,0.010003,0.010003
100003,3,484191.00,1035882.0,1452573.0,56553.990,98356.995,169661.970,435436.50,900000.0,1306309.5,3442.5,6885.0,6885.0,435436.5,900000.0,1306309.5,0.000000,0.100061,0.050030,-2341,-746,-1305.0,10.0,30.0,-48754.5,756.0,-146263.5,1.057664,1.150980,0.0,0.0,0.0,1.0,1.0,50.0,150.0,150.0,0.015272,0.018533
100004,1,20106.00,20106.0,20106.0,5357.250,5357.250,5357.250,24282.00,24282.0,24282.0,4860.0,4860.0,4860.0,24282.0,24282.0,24282.0,0.212008,0.212008,0.212008,-815,-815,-815.0,4.0,4.0,4176.0,4176.0,4176.0,0.828021,0.828021,0.0,0.0,0.0,1.0,1.0,30.0,30.0,30.0,0.016450,0.016450
100005,2,20076.75,40153.5,40153.5,4813.200,4813.200,4813.200,22308.75,44617.5,44617.5,4464.0,4464.0,4464.0,44617.5,44617.5,44617.5,0.108964,0.108964,0.108964,-757,-315,-536.0,12.0,12.0,2232.0,4464.0,4464.0,0.899950,0.899950,0.0,0.0,0.0,1.0,1.0,90.0,90.0,90.0,0.036537,0.036537

#### SK_ID_CURR별로 NAME_CONTRACT_STATUS가 Refused 일 경우의 건수 및 과거 대출건 대비 비율

#### Group by 기준  컬럼 기반에서 다른 컬럼들의 기준에 따라 세분화된 aggregation 수행.

In [ ]:
prev['NAME_CONTRACT_STATUS'].value_counts()

Approved        1036781
Canceled         316319
Refused          290678
Unused offer      26436
Name: NAME_CONTRACT_STATUS, dtype: int64

##### Pandas는 원 DataFrame 에 groupby 적용된 DataFrame 과 세부기준으로 filtering 된 DataFrame에 groupby 적용된 DataFrame 을 조인하여 생성. 
* NAME_CONTRACT_STATUS == 'Refused' 세부 기준으로 filtering 및 filtering 된 DataFrame에 groupby 적용 
* groupby 완료 후 기존 prev_amt_agg와 조인
* 효율적인 오류 방지를 위해서 groupby 시 적용후 groupby key값을 DataFrame의 Index가 아닌 일반 컬럼으로 변경.

In [ ]:
# NAME_CONTRACT_STATUS == 'Refused' 세부 기준으로 filtering 
cond_refused = (prev['NAME_CONTRACT_STATUS'] == 'Refused')
prev_refused = prev[cond_refused]
prev_refused.shape, prev.shape

((290678, 44), (1670214, 44))

In [ ]:
# NAME_CONTRACT_STATUS == 'Refused' 세부 기준으로 filtering 된 DataFrame에 groupby 적용 
prev_refused_agg = prev_refused.groupby(['SK_ID_CURR'])['SK_ID_CURR'].count()
print(prev_amt_agg.shape, prev_refused_agg .shape)
prev_refused_agg.head(10)

(338857, 39) (118277,)

SK_ID_CURR
100006     1
100011     1
100027     1
100030    10
100035     8
100036     3
100037     2
100043     5
100046     1
100047     2
Name: SK_ID_CURR, dtype: int64

In [ ]:
# prev_refused_agg은 Series객체이고 Index는 SK_ID_CURR, prev_amt_agg은 DataFrame, Index는 SK_ID_CURR. 하지만 JOIN되지 않는다. 
# Series와 DataFrame 조인 시 Series를 DataFrame으로 내부 변환하는데 조인 시 Index명과 컬럼명이 서로 충돌하여 오류. 
# prev_amt_refused_agg = prev_amt_agg.merge(prev_refused_agg, on='SK_ID_CURR', how='left')

pd.DataFrame(prev_refused_agg)

# 일반적으로 groupby key를 INDEX로 하는 것보다 일반 컬럼으로 하는 것이 여러가지 오류 예방에 효율적. 
prev_refused_agg = prev_refused_agg.reset_index(name='PREV_REFUSED_COUNT')
prev_amt_agg = prev_amt_agg.reset_index()

prev_amt_refused_agg = prev_amt_agg.merge(prev_refused_agg, on='SK_ID_CURR', how='left')
prev_amt_refused_agg.head()

,SK_ID_CURR,PREV_SK_ID_CURR_COUNT,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_SUM,PREV_AMT_ANNUITY_MEAN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_SUM,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_SUM,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MAX,PREV_AMT_DOWN_PAYMENT_SUM,PREV_AMT_GOODS_PRICE_MEAN,PREV_AMT_GOODS_PRICE_MAX,PREV_AMT_GOODS_PRICE_SUM,PREV_RATE_DOWN_PAYMENT_MIN,PREV_RATE_DOWN_PAYMENT_MAX,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_DAYS_DECISION_MIN,PREV_DAYS_DECISION_MAX,PREV_DAYS_DECISION_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_CNT_PAYMENT_SUM,PREV_PREV_CREDIT_DIFF_MEAN,PREV_PREV_CREDIT_DIFF_MAX,PREV_PREV_CREDIT_DIFF_SUM,PREV_PREV_CREDIT_APPL_RATIO_MEAN,PREV_PREV_CREDIT_APPL_RATIO_MAX,PREV_PREV_GOODS_DIFF_MEAN,PREV_PREV_GOODS_DIFF_MAX,PREV_PREV_GOODS_DIFF_SUM,PREV_PREV_GOODS_APPL_RATIO_MEAN,PREV_PREV_GOODS_APPL_RATIO_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_MEAN,PREV_PREV_DAYS_LAST_DUE_DIFF_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_SUM,PREV_PREV_INTERESTS_RATE_MEAN,PREV_PREV_INTERESTS_RATE_MAX,PREV_REFUSED_COUNT
0,100001,1,23787.00,23787.0,23787.0,3951.000,3951.000,3951.000,24835.50,24835.5,24835.5,2520.0,2520.0,2520.0,24835.5,24835.5,24835.5,0.104326,0.104326,0.104326,-1740,-1740,-1740.0,8.0,8.0,1048.5,1048.5,1048.5,0.957782,0.957782,0.0,0.0,0.0,1.0,1.0,120.0,120.0,120.0,0.041099,0.041099,NaN
1,100002,1,179055.00,179055.0,179055.0,9251.775,9251.775,9251.775,179055.00,179055.0,179055.0,0.0,0.0,0.0,179055.0,179055.0,179055.0,0.000000,0.000000,0.000000,-606,-606,-606.0,24.0,24.0,0.0,0.0,0.0,1.000000,1.000000,0.0,0.0,0.0,1.0,1.0,150.0,150.0,150.0,0.010003,0.010003,NaN
2,100003,3,484191.00,1035882.0,1452573.0,56553.990,98356.995,169661.970,435436.50,900000.0,1306309.5,3442.5,6885.0,6885.0,435436.5,900000.0,1306309.5,0.000000,0.100061,0.050030,-2341,-746,-1305.0,10.0,30.0,-48754.5,756.0,-146263.5,1.057664,1.150980,0.0,0.0,0.0,1.0,1.0,50.0,150.0,150.0,0.015272,0.018533,NaN
3,100004,1,20106.00,20106.0,20106.0,5357.250,5357.250,5357.250,24282.00,24282.0,24282.0,4860.0,4860.0,4860.0,24282.0,24282.0,24282.0,0.212008,0.212008,0.212008,-815,-815,-815.0,4.0,4.0,4176.0,4176.0,4176.0,0.828021,0.828021,0.0,0.0,0.0,1.0,1.0,30.0,30.0,30.0,0.016450,0.016450,NaN
4,100005,2,20076.75,40153.5,40153.5,4813.200,4813.200,4813.200,22308.75,44617.5,44617.5,4464.0,4464.0,4464.0,44617.5,44617.5,44617.5,0.108964,0.108964,0.108964,-757,-315,-536.0,12.0,12.0,2232.0,4464.0,4464.0,0.899950,0.899950,0.0,0.0,0.0,1.0,1.0,90.0,90.0,90.0,0.036537,0.036537,NaN

##### 계산된 PREV_REFUSED_COUNT 중 Null값은 0 으로 변경하고 SK_ID_CURR 개별 건수 대비 PREV_REFUSED_COUNT 비율 계산

In [ ]:
prev_amt_refused_agg['PREV_REFUSED_COUNT'].value_counts(dropna=False)

NaN     220580
1.0      54616
2.0      26793
3.0      14025
4.0       8243
5.0       4859
6.0       3147
7.0       2069
8.0       1247
9.0        871
10.0       656
11.0       437
12.0       340
13.0       233
14.0       157
15.0       149
16.0        94
17.0        62
18.0        54
19.0        48
20.0        28
21.0        25
22.0        21
24.0        18
25.0        12
26.0        11
23.0        11
27.0         8
29.0         5
28.0         5
32.0         4
31.0         3
41.0         3
30.0         3
37.0         3
33.0         2
34.0         2
39.0         2
35.0         2
36.0         2
47.0         1
43.0         1
64.0         1
54.0         1
58.0         1
51.0         1
68.0         1
Name: PREV_REFUSED_COUNT, dtype: int64

In [ ]:
# REFUSED_COUNT가 NaN인 데이터는 과거 대출신청시 Refused가 없는 것임. 따라서 0으로 치환해야함. 
prev_amt_refused_agg['PREV_REFUSED_COUNT'] = prev_amt_refused_agg['PREV_REFUSED_COUNT'].fillna(0)
# SK_ID_CURR별 과거 대출건수 대비 REFUSED_COUNT 비율 생성. 
prev_amt_refused_agg['PREV_REFUSED_RATIO'] = prev_amt_refused_agg['PREV_REFUSED_COUNT']/prev_amt_refused_agg['PREV_SK_ID_CURR_COUNT']

In [ ]:
prev_amt_refused_agg.head(30)

,SK_ID_CURR,PREV_SK_ID_CURR_COUNT,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_SUM,PREV_AMT_ANNUITY_MEAN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_SUM,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_SUM,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MAX,PREV_AMT_DOWN_PAYMENT_SUM,PREV_AMT_GOODS_PRICE_MEAN,PREV_AMT_GOODS_PRICE_MAX,PREV_AMT_GOODS_PRICE_SUM,PREV_RATE_DOWN_PAYMENT_MIN,PREV_RATE_DOWN_PAYMENT_MAX,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_DAYS_DECISION_MIN,PREV_DAYS_DECISION_MAX,PREV_DAYS_DECISION_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_CNT_PAYMENT_SUM,PREV_PREV_CREDIT_DIFF_MEAN,PREV_PREV_CREDIT_DIFF_MAX,PREV_PREV_CREDIT_DIFF_SUM,PREV_PREV_CREDIT_APPL_RATIO_MEAN,PREV_PREV_CREDIT_APPL_RATIO_MAX,PREV_PREV_GOODS_DIFF_MEAN,PREV_PREV_GOODS_DIFF_MAX,PREV_PREV_GOODS_DIFF_SUM,PREV_PREV_GOODS_APPL_RATIO_MEAN,PREV_PREV_GOODS_APPL_RATIO_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_MEAN,PREV_PREV_DAYS_LAST_DUE_DIFF_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_SUM,PREV_PREV_INTERESTS_RATE_MEAN,PREV_PREV_INTERESTS_RATE_MAX,PREV_REFUSED_COUNT,PREV_REFUSED_RATIO
0,100001,1,23787.000000,23787.0,23787.000,3951.000000,3951.000,3951.000,24835.500000,24835.5,24835.500,2520.000000,2520.0,2520.00,24835.500000,24835.5,24835.500,0.104326,0.104326,0.104326,-1740,-1740,-1740.000000,8.000000,8.0,1048.500000,1048.5,1048.50,0.957782,0.957782,0.0,0.0,0.0,1.0,1.0,120.00,120.0,120.0,0.041099,0.041099,0.0,0.000000
1,100002,1,179055.000000,179055.0,179055.000,9251.775000,9251.775,9251.775,179055.000000,179055.0,179055.000,0.000000,0.0,0.00,179055.000000,179055.0,179055.000,0.000000,0.000000,0.000000,-606,-606,-606.000000,24.000000,24.0,0.000000,0.0,0.00,1.000000,1.000000,0.0,0.0,0.0,1.0,1.0,150.00,150.0,150.0,0.010003,0.010003,0.0,0.000000
2,100003,3,484191.000000,1035882.0,1452573.000,56553.990000,98356.995,169661.970,435436.500000,900000.0,1306309.500,3442.500000,6885.0,6885.00,435436.500000,900000.0,1306309.500,0.000000,0.100061,0.050030,-2341,-746,-1305.000000,10.000000,30.0,-48754.500000,756.0,-146263.50,1.057664,1.150980,0.0,0.0,0.0,1.0,1.0,50.00,150.0,150.0,0.015272,0.018533,0.0,0.000000
3,100004,1,20106.000000,20106.0,20106.000,5357.250000,5357.250,5357.250,24282.000000,24282.0,24282.000,4860.000000,4860.0,4860.00,24282.000000,24282.0,24282.000,0.212008,0.212008,0.212008,-815,-815,-815.000000,4.000000,4.0,4176.000000,4176.0,4176.00,0.828021,0.828021,0.0,0.0,0.0,1.0,1.0,30.00,30.0,30.0,0.016450,0.016450,0.0,0.000000
4,100005,2,20076.750000,40153.5,40153.500,4813.200000,4813.200,4813.200,22308.750000,44617.5,44617.500,4464.000000,4464.0,4464.00,44617.500000,44617.5,44617.500,0.108964,0.108964,0.108964,-757,-315,-536.000000,12.000000,12.0,2232.000000,4464.0,4464.00,0.899950,0.899950,0.0,0.0,0.0,1.0,1.0,90.00,90.0,90.0,0.036537,0.036537,0.0,0.000000
5,100006,9,291695.500000,906615.0,2625259.500,23651.175000,39954.510,141907.050,272203.260000,688500.0,2449829.340,34840.170000,66987.0,69680.34,408304.890000,688500.0,2449829.340,0.108994,0.217830,0.163412,-617,-181,-272.444444,23.000000,138.0,-19492.240000,66987.0,-175430.16,1.012684,1.316797,0.0,0.0,0.0,1.0,1.0,810.00,1410.0,1620.0,-inf,0.027424,1.0,0.111111
6,100007,6,166638.750000,284400.0,999832.500,12278.805000,22678.785,73672.830,150530.250000,247500.0,903181.500,3390.750000,3676.5,6781.50,150530.250000,247500.0,903181.500,0.100143,0.218890,0.159516,-2357,-374,-1222.833333,20.666667,124.0,-16108.500000,2560.5,-96651.00,1.046356,1.264000,0.0,0.0,0.0,1.0,1.0,7.50,30.0,30.0,0.026538,0.036164,0.0,0.000000
7,100008,5,162767.700000,501975.0,813838.500,15839.696250,25309.575,63358.785,155701.800000,450000.0,778509.000,5548.500000,12145.5,16645.50,194627.250000,450000.0,778509.000,0.000000,0.110243,0.073051,-2536,-82,-1192.000000,14.000000,56.0,-7065.900000,12145.5,-35329.50,0.978569,1.115500,0.0,0.0,0.0,1.0,1.0,165.00,660.0,660.0,0.018055,0.034034,0.0,0.000000
8,100009,7,70137.642857,98239.5,490963.500,10051.412143,17341.605,70359.885,76741.714286,110160.0,537192.000,9203.142857,22032.0,64422.00,76741.714286,110160.0,537192.000,0.000000,0.209525,0.126602,-1562,-74,-719.285714,8.000000,56.0,6604.071429,17671.5,46228.50,0.916226,1.000000,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.019536,0.030703,0.0,0.000000
9,100010,1,260811.000000,260811.0,260811.000,27463.410000,27463.410,27463.410,247212.000000,247212.0,247212.000,0.000000,0.0,0.00,247212.000000,247212.0,247212.000,0.000000,0.000000,0.000000,-1070,-1070,-1070.000000,10.000000,10.0,-13599.000000,-13599.0,-13599.00,1.055009,1.055009,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.005300,0.005300,0.0,0.000000
10,100011,4,261840.375000,732915.0,1047361.500,18303.195000,31295.250,54909.585,202732.875000,675000.0,810931.500,6797.250000,13594.5,13594.50,270310.500000,675000.0,810931.500,0.000000,0.100010,0.050005,-2508,-1162,-1784.500000,14.000000,42.0,-59107.500000,1485.0,-236430.00,inf,inf,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,-inf,0.025367,1.0,0.250000
11,100012,4,74119.500000,158508.0,296478.000,7894.155000,11188.035,23682.465,60930.000000,135000.0,243720.000,0.000000,0.0,0.00,81240.000000,135000.0,243720.000,0.000000,0.000000,0.000000,-1673,-107,-779.750000,18.000000,54.0,-13189.500000,0.0,-52758.00,1.236566,1.269700,0.0,0.0,0.0,1.0,1.0,100.00,180.0,300.0,0.033372,0.043775,0.0,0.000000
12,100013,4,146134.125000,512370.0,584536.500,11478.195000,23153.985,34434.585,130871.250000,450000.0,523485.000,3375.000000,6750.0,6750.00,174495.000000,450000.0,523485.000,0.000000,0.134434,0.067217,-1999,-222,-837.500000,17.333333,52.0,-15262.875000,3096.0,-61051.50,1.052363,1.138600,0.0,0.0,0.0,1.0,1.0,200.00,570.0,600.0,0.027617,0.036400,0.0,0.000000
13,100014,2,102834.000000,131868.0,205668.000,12806.550000,14045.625,25613.100,96536.250000,119272.5,193072.500,0.000000,0.0,0.00,96536.250000,119272.5,193072.500,0.000000,0.000000,0.000000,-844,-102,-473.000000,9.000000,18.0,-6297.750000,0.0,-12595.50,1.052801,1.105603,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014020,0.023653,0.0,0.000000
14,100015,1,67077.000000,67077.0,67077.000,7666.920000,7666.920,7666.920,68850.000000,68850.0,68850.000,6885.000000,6885.0,6885.00,68850.000000,68850.0,68850.000,0.101382,0.101382,0.101382,-2396,-2396,-2396.000000,10.000000,10.0,1773.000000,1773.0,1773.00,0.974248,0.974248,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014300,0.014300,0.0,0.000000
15,100016,4,106221.375000,232200.0,424885.500,8593.155000,14480.460,34372.620,120745.125000,290250.0,482980.500,15690.375000,58050.0,62761.50,120745.125000,290250.0,482980.500,0.000000,0.217818,0.081682,-2370,-1049,-1779.500000,17.000000,68.0,14523.750000,58050.0,58095.00,0.949761,1.099045,0.0,0.0,0.0,1.0,1.0,70.00,210.0,210.0,0.029580,0.033600,0.0,0.000000
16,100017,2,175565.250000,198409.5,351130.500,14375.407500,16967.295,28750.815,176665.500000,195291.0,353331.000,19152.000000,22500.0,38304.00,176665.500000,195291.0,353331.000,0.102133,0.110926,0.106529,-2441,-612,-1526.500000,17.000000,34.0,1100.250000,5319.0,2200.50,0.991156,1.015968,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014412,0.017723,0.0,0.000000
17,100018,4,285989.591250,536364.0,1143958.365,38669.703750,94906.035,154678.815,298363.466250,571774.5,1193453.865,14295.375000,57181.5,57181.50,298363.466250,571774.5,1193453.865,0.000000,0.108917,0.027229,-1648,-188,-755.250000,10.000000,40.0,12373.875000,57181.5,49495.50,1.014609,1.158442,0.0,0.0,0.0,1.0,1.0,-9.00,0.0,-18.0,0.018384,0.038257,0.0,0.000000
18,100019,1,104683.500000,104683.5,104683.500,10518.615000,10518.615,10518.615,84136.500000,84136.5,84136.500,0.000000,0.0,0.00,84136.500000,84136.5,84136.500,0.000000,0.000000,0.000000,-925,-925,-925.000000,12.000000,12.0,-20547.000000,-20547.0,-20547.00,1.244210,1.244210,0.0,0.0,0.0,1.0,1.0,150.00,150.0,150.0,0.017147,0.017147,0.0,0.000000
19,100020,2,41706.000000,48325.5,83412.000,7254.517500,8779.770,14509.035,39206.250000,45900.0,78412.500,0.000000,0.0,0.00,39206.250000,45900.0,78412.500,0.000000,0.000000,0.000000,-472,-243,-357.500000,7.000000,14.0,-2499.750000,-2425.5,-4999.50,1.066006,1.079170,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.026651,0.038290,0.0,0.000000
20,100021,6,153615.750000,675000.0,921694.500,10686.165000,33750.000,64116.990,40961.250000,99189.0,245767.500,3770.100000,9922.5,18850.50,49153.500000,99189.0,245767.500,0.000000,0.433539,0.106606,-2811,-261,-943.833333,7.000000,42.0,-112654.500000,8928.0,-675927.00,inf,inf,0.0,0.0,0.0,1.0,1.0,90.00,180.0,270.0,-inf,0.034033,0.0,0.000000
21,100022,1,103203.000000,103203.0,103203.000,6765.975000,6765.975,6765.975,89091.000000,89091.0,89091.000,0.000000,0.0,0.00,89091.000000,89091.0,89091.000,0.000000,0.000000,0.000000,-239,-239,-239.000000,18.000000,18.0,-14112.000000,-14112.0,-14112.00,1.158400,1.158400,0.0,0.0,0.0,1.0,1.0,NaN,NaN,0.0,0.010004,0.010004,0.0,0.000000
22,100023,4,113517.000000,239242.5,454068.000,8895.892500,16822.440,35583.570,98746.875000,180000.0,394987.500,8435.250000,9000.0,16870.50,98746.875000,180000.0,394987.500,0.095959,0.101380,0.098669,-2424,-262,-1215.750000,12.500000,50.0,-14770.125000,2025.0,-59080.50,1.080951,1.329125,0.0,0.0,0.0,1.0,1.0,240.00,600.0,720.0,-inf,0.028649,0.0,0.000000
23,100025,8,295425.781875,1042560.0,2363406.255,27645.595714,55678.095,193519.170,259795.344375,900000.0,2078362.755,5845.500000,23382.0,23382.00,296908.965000,900000.0,2078362.755,0.000000,0.423065,0.105766,-2060,-7,-731.000000,13.714286,96.0,-35630.437500,21645.0,-285043.50,1.073930,1.269700,0.0,0.0,0.0,1.0,1.0,174.25,367.0,697.0,0.022884,0.027871,0.0,0.000000
24,100026,3,292281.000000,744498.0,876843.000,33193.665000,42778.845,66387.330,269115.000000,675000.0,807345.000,0.000000,0.0,0.00,403672.500000,675000.0,807345.000,0.000000,0.000000,0.000000,-1427,-152,-682.333333,21.000000,42.0,-23166.000000,0.0,-69498.00,1.051480,1.102960,0.0,0.0,0.0,1.0,1.0,510.00,1020.0,1020.0,0.020701,0.029682,0.0,0.000000
25,100027,4,173795.625000,239850.0,695182.500,24067.755000,28077.570,72203.265,163621.125000,226984.5,654484.500,0.000000,0.0,0.00,218161.500000,226984.5,654484.500,0.000000,0.000000,0.000000,-795,-181,-407.000000,11.333333,34.0,-10174.500000,0.0,-40698.00,1.062332,1.066000,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014849,0.017250,1.0,0.250000
26,100028,5,92920.500000,225000.0,464602.500,8091.585000,11250.000,24274.755,49207.500000,130765.5,246037.500,3750.000000,11250.0,11250.00,82012.500000,130765.5,246037.500,0.000000,0.173124,0.057708,-1805,-531,-1124.200000,11.333333,34.0,-43713.000000,6435.0,-218565.00,inf,inf,0.0,0.0,0.0,1.0,1.0,75.00,150.0,150.0,-inf,0.017550,0.0,0.000000
27,100029,1,126000.000000,126000.0,126000.000,22891.680000,22891.680,22891.680,126000.000000,126000.0,126000.000,0.000000,0.0,0.00,126000.000000,126000.0,126000.000,0.000000,0.000000,0.000000,-324,-324,-324.000000,6.000000,6.0,0.000000,0.0,0.00,1.000000,1.000000,0.0,0.0,0.0,1.0,1.0,60.00,60.0,60.0,0.015013,0.015013,0.0,0.000000
28,100030,12,32534.643750,49734.0,390415.725,4731.041250,9035.685,37848.330,33497.268750,47241.0,401967.225,1262.625000,6714.0,15151.50,33497.268750,47241.0,401967.225,0.000000,0.210919,0.044804,-2856,-378,-1981.083333,8.625000,69.0,962.625000,5607.0,11551.50,0.965475,1.052772,0.0,0.0,0.0,1.0,1.0,60.00,90.0,120.0,0.017772,0.037233,10.0,0.833333
29,100032,1,42255.000000,42255.0,42255.000,7910.145000,7910.145,7910.145,69255.000000,69255.0,69255.000,27000.000000,27000.0,27000.00,69255.000000,69255.0,69255.000,0.424597,0.424597,0.424597,-1497,-1497,-1497.000000,6.000000,6.0,27000.000000,27000.0,27000.00,0.610136,0.610136,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.020534,0.020534,0.0,0.000000

In [ ]:
# 원래 groupby 컬럼 + 세부 기준 컬럼으로 groupby 수행. 세분화된 레벨로 aggregation 수행 한 뒤에 unstack()으로 컬럼레벨로 변형. 
prev_refused_appr_group = prev[prev['NAME_CONTRACT_STATUS'].isin(['Approved', 'Refused'])].groupby([ 'SK_ID_CURR', 'NAME_CONTRACT_STATUS'])
prev_refused_appr_agg = prev_refused_appr_group['SK_ID_CURR'].count().unstack()
prev_refused_appr_agg.head(30)

NAME_CONTRACT_STATUS  Approved  Refused
SK_ID_CURR
100001                     1.0      NaN
100002                     1.0      NaN
100003                     3.0      NaN
100004                     1.0      NaN
100005                     1.0      NaN
100006                     5.0      1.0
100007                     6.0      NaN
100008                     4.0      NaN
100009                     7.0      NaN
100010                     1.0      NaN
100011                     3.0      1.0
100012                     3.0      NaN
100013                     3.0      NaN
100014                     2.0      NaN
100015                     1.0      NaN
100016                     4.0      NaN
100017                     2.0      NaN
100018                     4.0      NaN
100019                     1.0      NaN
100020                     2.0      NaN
100021                     6.0      NaN
100022                     1.0      NaN
100023                     4.0      NaN
100025                     7.0      NaN
100026                     2.0      NaN
100027                     2.0      1.0
100028                     3.0      NaN
100029                     1.0      NaN
100030                     2.0     10.0
100032                     1.0      NaN

#####  컬럼명 변경, Null 처리, 그리고 기존의 prev_amt_agg와 조인 후 데이터 가공

In [ ]:
# 컬럼명 변경. 
prev_refused_appr_agg.columns = ['PREV_APPROVED_COUNT', 'PREV_REFUSED_COUNT' ]
# NaN값은 모두 0으로 변경. 
prev_refused_appr_agg = prev_refused_appr_agg.fillna(0)

In [ ]:
prev_refused_appr_agg.head()

            PREV_APPROVED_COUNT  PREV_REFUSED_COUNT
SK_ID_CURR
100001                      1.0                 0.0
100002                      1.0                 0.0
100003                      3.0                 0.0
100004                      1.0                 0.0
100005                      1.0                 0.0

In [ ]:
# prev_amt_agg와 조인. prev_amt_agg와 prev_refused_appr_agg 모두 SK_ID_CURR을 INDEX로 가지고 있음. 
prev_agg = prev_amt_agg.merge(prev_refused_appr_agg, on='SK_ID_CURR', how='left')
# SK_ID_CURR별 과거 대출건수 대비 APPROVED_COUNT 및 REFUSED_COUNT 비율 생성. 
prev_agg['PREV_REFUSED_RATIO'] = prev_agg['PREV_REFUSED_COUNT']/prev_agg['PREV_SK_ID_CURR_COUNT']
prev_agg['PREV_APPROVED_RATIO'] = prev_agg['PREV_APPROVED_COUNT']/prev_agg['PREV_SK_ID_CURR_COUNT']
# 'PREV_REFUSED_COUNT', 'PREV_APPROVED_COUNT' 컬럼 drop 
prev_agg = prev_agg.drop(['PREV_REFUSED_COUNT', 'PREV_APPROVED_COUNT'], axis=1)
# prev_amt_agg와 prev_refused_appr_agg INDEX인 SK_ID_CURR이 조인 후 정식 컬럼으로 생성됨. 
prev_agg.head(30)

,SK_ID_CURR,PREV_SK_ID_CURR_COUNT,PREV_AMT_CREDIT_MEAN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_SUM,PREV_AMT_ANNUITY_MEAN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_SUM,PREV_AMT_APPLICATION_MEAN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_SUM,PREV_AMT_DOWN_PAYMENT_MEAN,PREV_AMT_DOWN_PAYMENT_MAX,PREV_AMT_DOWN_PAYMENT_SUM,PREV_AMT_GOODS_PRICE_MEAN,PREV_AMT_GOODS_PRICE_MAX,PREV_AMT_GOODS_PRICE_SUM,PREV_RATE_DOWN_PAYMENT_MIN,PREV_RATE_DOWN_PAYMENT_MAX,PREV_RATE_DOWN_PAYMENT_MEAN,PREV_DAYS_DECISION_MIN,PREV_DAYS_DECISION_MAX,PREV_DAYS_DECISION_MEAN,PREV_CNT_PAYMENT_MEAN,PREV_CNT_PAYMENT_SUM,PREV_PREV_CREDIT_DIFF_MEAN,PREV_PREV_CREDIT_DIFF_MAX,PREV_PREV_CREDIT_DIFF_SUM,PREV_PREV_CREDIT_APPL_RATIO_MEAN,PREV_PREV_CREDIT_APPL_RATIO_MAX,PREV_PREV_GOODS_DIFF_MEAN,PREV_PREV_GOODS_DIFF_MAX,PREV_PREV_GOODS_DIFF_SUM,PREV_PREV_GOODS_APPL_RATIO_MEAN,PREV_PREV_GOODS_APPL_RATIO_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_MEAN,PREV_PREV_DAYS_LAST_DUE_DIFF_MAX,PREV_PREV_DAYS_LAST_DUE_DIFF_SUM,PREV_PREV_INTERESTS_RATE_MEAN,PREV_PREV_INTERESTS_RATE_MAX,PREV_REFUSED_RATIO,PREV_APPROVED_RATIO
0,100001,1,23787.000000,23787.0,23787.000,3951.000000,3951.000,3951.000,24835.500000,24835.5,24835.500,2520.000000,2520.0,2520.00,24835.500000,24835.5,24835.500,0.104326,0.104326,0.104326,-1740,-1740,-1740.000000,8.000000,8.0,1048.500000,1048.5,1048.50,0.957782,0.957782,0.0,0.0,0.0,1.0,1.0,120.00,120.0,120.0,0.041099,0.041099,0.000000,1.000000
1,100002,1,179055.000000,179055.0,179055.000,9251.775000,9251.775,9251.775,179055.000000,179055.0,179055.000,0.000000,0.0,0.00,179055.000000,179055.0,179055.000,0.000000,0.000000,0.000000,-606,-606,-606.000000,24.000000,24.0,0.000000,0.0,0.00,1.000000,1.000000,0.0,0.0,0.0,1.0,1.0,150.00,150.0,150.0,0.010003,0.010003,0.000000,1.000000
2,100003,3,484191.000000,1035882.0,1452573.000,56553.990000,98356.995,169661.970,435436.500000,900000.0,1306309.500,3442.500000,6885.0,6885.00,435436.500000,900000.0,1306309.500,0.000000,0.100061,0.050030,-2341,-746,-1305.000000,10.000000,30.0,-48754.500000,756.0,-146263.50,1.057664,1.150980,0.0,0.0,0.0,1.0,1.0,50.00,150.0,150.0,0.015272,0.018533,0.000000,1.000000
3,100004,1,20106.000000,20106.0,20106.000,5357.250000,5357.250,5357.250,24282.000000,24282.0,24282.000,4860.000000,4860.0,4860.00,24282.000000,24282.0,24282.000,0.212008,0.212008,0.212008,-815,-815,-815.000000,4.000000,4.0,4176.000000,4176.0,4176.00,0.828021,0.828021,0.0,0.0,0.0,1.0,1.0,30.00,30.0,30.0,0.016450,0.016450,0.000000,1.000000
4,100005,2,20076.750000,40153.5,40153.500,4813.200000,4813.200,4813.200,22308.750000,44617.5,44617.500,4464.000000,4464.0,4464.00,44617.500000,44617.5,44617.500,0.108964,0.108964,0.108964,-757,-315,-536.000000,12.000000,12.0,2232.000000,4464.0,4464.00,0.899950,0.899950,0.0,0.0,0.0,1.0,1.0,90.00,90.0,90.0,0.036537,0.036537,0.000000,0.500000
5,100006,9,291695.500000,906615.0,2625259.500,23651.175000,39954.510,141907.050,272203.260000,688500.0,2449829.340,34840.170000,66987.0,69680.34,408304.890000,688500.0,2449829.340,0.108994,0.217830,0.163412,-617,-181,-272.444444,23.000000,138.0,-19492.240000,66987.0,-175430.16,1.012684,1.316797,0.0,0.0,0.0,1.0,1.0,810.00,1410.0,1620.0,-inf,0.027424,0.111111,0.555556
6,100007,6,166638.750000,284400.0,999832.500,12278.805000,22678.785,73672.830,150530.250000,247500.0,903181.500,3390.750000,3676.5,6781.50,150530.250000,247500.0,903181.500,0.100143,0.218890,0.159516,-2357,-374,-1222.833333,20.666667,124.0,-16108.500000,2560.5,-96651.00,1.046356,1.264000,0.0,0.0,0.0,1.0,1.0,7.50,30.0,30.0,0.026538,0.036164,0.000000,1.000000
7,100008,5,162767.700000,501975.0,813838.500,15839.696250,25309.575,63358.785,155701.800000,450000.0,778509.000,5548.500000,12145.5,16645.50,194627.250000,450000.0,778509.000,0.000000,0.110243,0.073051,-2536,-82,-1192.000000,14.000000,56.0,-7065.900000,12145.5,-35329.50,0.978569,1.115500,0.0,0.0,0.0,1.0,1.0,165.00,660.0,660.0,0.018055,0.034034,0.000000,0.800000
8,100009,7,70137.642857,98239.5,490963.500,10051.412143,17341.605,70359.885,76741.714286,110160.0,537192.000,9203.142857,22032.0,64422.00,76741.714286,110160.0,537192.000,0.000000,0.209525,0.126602,-1562,-74,-719.285714,8.000000,56.0,6604.071429,17671.5,46228.50,0.916226,1.000000,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.019536,0.030703,0.000000,1.000000
9,100010,1,260811.000000,260811.0,260811.000,27463.410000,27463.410,27463.410,247212.000000,247212.0,247212.000,0.000000,0.0,0.00,247212.000000,247212.0,247212.000,0.000000,0.000000,0.000000,-1070,-1070,-1070.000000,10.000000,10.0,-13599.000000,-13599.0,-13599.00,1.055009,1.055009,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.005300,0.005300,0.000000,1.000000
10,100011,4,261840.375000,732915.0,1047361.500,18303.195000,31295.250,54909.585,202732.875000,675000.0,810931.500,6797.250000,13594.5,13594.50,270310.500000,675000.0,810931.500,0.000000,0.100010,0.050005,-2508,-1162,-1784.500000,14.000000,42.0,-59107.500000,1485.0,-236430.00,inf,inf,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,-inf,0.025367,0.250000,0.750000
11,100012,4,74119.500000,158508.0,296478.000,7894.155000,11188.035,23682.465,60930.000000,135000.0,243720.000,0.000000,0.0,0.00,81240.000000,135000.0,243720.000,0.000000,0.000000,0.000000,-1673,-107,-779.750000,18.000000,54.0,-13189.500000,0.0,-52758.00,1.236566,1.269700,0.0,0.0,0.0,1.0,1.0,100.00,180.0,300.0,0.033372,0.043775,0.000000,0.750000
12,100013,4,146134.125000,512370.0,584536.500,11478.195000,23153.985,34434.585,130871.250000,450000.0,523485.000,3375.000000,6750.0,6750.00,174495.000000,450000.0,523485.000,0.000000,0.134434,0.067217,-1999,-222,-837.500000,17.333333,52.0,-15262.875000,3096.0,-61051.50,1.052363,1.138600,0.0,0.0,0.0,1.0,1.0,200.00,570.0,600.0,0.027617,0.036400,0.000000,0.750000
13,100014,2,102834.000000,131868.0,205668.000,12806.550000,14045.625,25613.100,96536.250000,119272.5,193072.500,0.000000,0.0,0.00,96536.250000,119272.5,193072.500,0.000000,0.000000,0.000000,-844,-102,-473.000000,9.000000,18.0,-6297.750000,0.0,-12595.50,1.052801,1.105603,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014020,0.023653,0.000000,1.000000
14,100015,1,67077.000000,67077.0,67077.000,7666.920000,7666.920,7666.920,68850.000000,68850.0,68850.000,6885.000000,6885.0,6885.00,68850.000000,68850.0,68850.000,0.101382,0.101382,0.101382,-2396,-2396,-2396.000000,10.000000,10.0,1773.000000,1773.0,1773.00,0.974248,0.974248,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014300,0.014300,0.000000,1.000000
15,100016,4,106221.375000,232200.0,424885.500,8593.155000,14480.460,34372.620,120745.125000,290250.0,482980.500,15690.375000,58050.0,62761.50,120745.125000,290250.0,482980.500,0.000000,0.217818,0.081682,-2370,-1049,-1779.500000,17.000000,68.0,14523.750000,58050.0,58095.00,0.949761,1.099045,0.0,0.0,0.0,1.0,1.0,70.00,210.0,210.0,0.029580,0.033600,0.000000,1.000000
16,100017,2,175565.250000,198409.5,351130.500,14375.407500,16967.295,28750.815,176665.500000,195291.0,353331.000,19152.000000,22500.0,38304.00,176665.500000,195291.0,353331.000,0.102133,0.110926,0.106529,-2441,-612,-1526.500000,17.000000,34.0,1100.250000,5319.0,2200.50,0.991156,1.015968,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014412,0.017723,0.000000,1.000000
17,100018,4,285989.591250,536364.0,1143958.365,38669.703750,94906.035,154678.815,298363.466250,571774.5,1193453.865,14295.375000,57181.5,57181.50,298363.466250,571774.5,1193453.865,0.000000,0.108917,0.027229,-1648,-188,-755.250000,10.000000,40.0,12373.875000,57181.5,49495.50,1.014609,1.158442,0.0,0.0,0.0,1.0,1.0,-9.00,0.0,-18.0,0.018384,0.038257,0.000000,1.000000
18,100019,1,104683.500000,104683.5,104683.500,10518.615000,10518.615,10518.615,84136.500000,84136.5,84136.500,0.000000,0.0,0.00,84136.500000,84136.5,84136.500,0.000000,0.000000,0.000000,-925,-925,-925.000000,12.000000,12.0,-20547.000000,-20547.0,-20547.00,1.244210,1.244210,0.0,0.0,0.0,1.0,1.0,150.00,150.0,150.0,0.017147,0.017147,0.000000,1.000000
19,100020,2,41706.000000,48325.5,83412.000,7254.517500,8779.770,14509.035,39206.250000,45900.0,78412.500,0.000000,0.0,0.00,39206.250000,45900.0,78412.500,0.000000,0.000000,0.000000,-472,-243,-357.500000,7.000000,14.0,-2499.750000,-2425.5,-4999.50,1.066006,1.079170,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.026651,0.038290,0.000000,1.000000
20,100021,6,153615.750000,675000.0,921694.500,10686.165000,33750.000,64116.990,40961.250000,99189.0,245767.500,3770.100000,9922.5,18850.50,49153.500000,99189.0,245767.500,0.000000,0.433539,0.106606,-2811,-261,-943.833333,7.000000,42.0,-112654.500000,8928.0,-675927.00,inf,inf,0.0,0.0,0.0,1.0,1.0,90.00,180.0,270.0,-inf,0.034033,0.000000,1.000000
21,100022,1,103203.000000,103203.0,103203.000,6765.975000,6765.975,6765.975,89091.000000,89091.0,89091.000,0.000000,0.0,0.00,89091.000000,89091.0,89091.000,0.000000,0.000000,0.000000,-239,-239,-239.000000,18.000000,18.0,-14112.000000,-14112.0,-14112.00,1.158400,1.158400,0.0,0.0,0.0,1.0,1.0,NaN,NaN,0.0,0.010004,0.010004,0.000000,1.000000
22,100023,4,113517.000000,239242.5,454068.000,8895.892500,16822.440,35583.570,98746.875000,180000.0,394987.500,8435.250000,9000.0,16870.50,98746.875000,180000.0,394987.500,0.095959,0.101380,0.098669,-2424,-262,-1215.750000,12.500000,50.0,-14770.125000,2025.0,-59080.50,1.080951,1.329125,0.0,0.0,0.0,1.0,1.0,240.00,600.0,720.0,-inf,0.028649,0.000000,1.000000
23,100025,8,295425.781875,1042560.0,2363406.255,27645.595714,55678.095,193519.170,259795.344375,900000.0,2078362.755,5845.500000,23382.0,23382.00,296908.965000,900000.0,2078362.755,0.000000,0.423065,0.105766,-2060,-7,-731.000000,13.714286,96.0,-35630.437500,21645.0,-285043.50,1.073930,1.269700,0.0,0.0,0.0,1.0,1.0,174.25,367.0,697.0,0.022884,0.027871,0.000000,0.875000
24,100026,3,292281.000000,744498.0,876843.000,33193.665000,42778.845,66387.330,269115.000000,675000.0,807345.000,0.000000,0.0,0.00,403672.500000,675000.0,807345.000,0.000000,0.000000,0.000000,-1427,-152,-682.333333,21.000000,42.0,-23166.000000,0.0,-69498.00,1.051480,1.102960,0.0,0.0,0.0,1.0,1.0,510.00,1020.0,1020.0,0.020701,0.029682,0.000000,0.666667
25,100027,4,173795.625000,239850.0,695182.500,24067.755000,28077.570,72203.265,163621.125000,226984.5,654484.500,0.000000,0.0,0.00,218161.500000,226984.5,654484.500,0.000000,0.000000,0.000000,-795,-181,-407.000000,11.333333,34.0,-10174.500000,0.0,-40698.00,1.062332,1.066000,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.014849,0.017250,0.250000,0.500000
26,100028,5,92920.500000,225000.0,464602.500,8091.585000,11250.000,24274.755,49207.500000,130765.5,246037.500,3750.000000,11250.0,11250.00,82012.500000,130765.5,246037.500,0.000000,0.173124,0.057708,-1805,-531,-1124.200000,11.333333,34.0,-43713.000000,6435.0,-218565.00,inf,inf,0.0,0.0,0.0,1.0,1.0,75.00,150.0,150.0,-inf,0.017550,0.000000,0.600000
27,100029,1,126000.000000,126000.0,126000.000,22891.680000,22891.680,22891.680,126000.000000,126000.0,126000.000,0.000000,0.0,0.00,126000.000000,126000.0,126000.000,0.000000,0.000000,0.000000,-324,-324,-324.000000,6.000000,6.0,0.000000,0.0,0.00,1.000000,1.000000,0.0,0.0,0.0,1.0,1.0,60.00,60.0,60.0,0.015013,0.015013,0.000000,1.000000
28,100030,12,32534.643750,49734.0,390415.725,4731.041250,9035.685,37848.330,33497.268750,47241.0,401967.225,1262.625000,6714.0,15151.50,33497.268750,47241.0,401967.225,0.000000,0.210919,0.044804,-2856,-378,-1981.083333,8.625000,69.0,962.625000,5607.0,11551.50,0.965475,1.052772,0.0,0.0,0.0,1.0,1.0,60.00,90.0,120.0,0.017772,0.037233,0.833333,0.166667
29,100032,1,42255.000000,42255.0,42255.000,7910.145000,7910.145,7910.145,69255.000000,69255.0,69255.000,27000.000000,27000.0,27000.00,69255.000000,69255.0,69255.000,0.424597,0.424597,0.424597,-1497,-1497,-1497.000000,6.000000,6.0,27000.000000,27000.0,27000.00,0.610136,0.610136,0.0,0.0,0.0,1.0,1.0,0.00,0.0,0.0,0.020534,0.020534,0.000000,1.000000

#### 가공된 최종 데이터 세트 생성
##### 지금까지 과정을 함수화
##### 이전에 application 데이터 세트의 feature engineering 수행 후 새롭게 previous 데이터 세트로 가공된 데이터를 조인.

In [ ]:
import numpy as np
import pandas as pd
import gc
import time
import matplotlib.pyplot as plt
import seaborn as sns
import os
%matplotlib inline

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 200)

In [ ]:
def get_dataset():
    app_train = pd.read_csv('application_train.csv')
    app_test = pd.read_csv('application_test.csv')
    apps = pd.concat([app_train, app_test])
    prev = pd.read_csv('previous_application.csv')

    return apps, prev

apps, prev = get_dataset()